services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library-db
      TZ: Asia/Seoul
    ports:
      - 3306:3306
