services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:    
      MYSQL_DATABASE: myblog
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306 