services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:    
      MYSQL_DATABASE: myblog
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306 
    networks:
      - mynet

  blog-api:
    depends_on:
      - mysql-db
    build:
      context: .
    image: blog-rest-api
    container_name: blog-rest-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/myblog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME : user1
      SPRING_DATASOURCE_PASSWORD : 1234
    ports:
      - 8080:8080  
    networks:
      - mynet

networks:
  mynet: